/*
 * This source file was generated by the Gradle 'init' task
 */
import org.junit.Test;

public class OrderCountJsonReaderTest {
    @Test public void test() {
      System.out.println("sample");
    }
}
